### ISSUE TITLE
GNU Radio examples are mixed with those from `M17_Implementations`

### ISSUE THREAD

**Issue by sp5wwp** [M17-Project/gr-m17#10]
Bring order to `gr-m17/examples` and `M17_Implementations/SP5WWP/grc`.

**Comment by sp5wwp** [comment]
@jmfriedt I think the old files in the `/examples` directory, [NFM_M17.grc](https://github.com/M17-Project/gr-m17/blob/main/examples/NFM_M17.grc), [NFM_simulation.grc](https://github.com/M17-Project/gr-m17/blob/main/examples/NFM_simulation.grc), can be removed.

[m17_streamer.grc](https://github.com/M17-Project/gr-m17/blob/main/examples/m17_streamer.grc) along with the .png file might need an update.

**Comment by jmfriedt** [comment]
I'd rather make these examples functional than remove them in order to demonstrate a realistic link or provide a framework for BER analysis in addition to the loopback test of m17_streamer.grc if possible.

**Comment by sp5wwp** [comment]
I'll update them both ASAP.

**Comment by jmfriedt** [comment]
NFM* examples were removed and the transmitterPLUTOSDR/receiverRTLSDR examples provide a realistic usage case over the air communication, as well as m17_loopback_noisychannel for synthetic data. I believe the grc file in M17_Implementations/SP5WWP/grc is independent of gr-m17 so there is no overlap in these demonstrations.
