### ISSUE TITLE
m17_decoder block doesn't work with noisy symbol streams

### ISSUE THREAD

**Issue by sp5wwp** [M17-Project/gr-m17#11]
How to reproduce:
1. Run `examples/m17_loopback_noisy.grc`
2. Observe how the decoder works with no noise applied to the symbol stream (default state).
3. Add a little Gaussian noise to the stream - even 0.01 is enough.
4. The decoder breaks and outputs malformed data.

**Comment by jmfriedt** [comment]
Is this a GNU Radio issue or a decoder issue with an excessive sensitivity to noise of the soft to hard bit decoder?

**Comment by sp5wwp** [comment]
I believe I have fixed the bug. Can you update the submodule? One change that you have to make in your code is to replace the whole header file list (long!) with a single <m17/m17.h>.

**Comment by sp5wwp** [comment]
I'll test ASAP and close this issue if it's no longer relevant.

**Comment by sp5wwp** [comment]
Works fine!
