### ISSUE TITLE
SRC/DST IDs

### ISSUE THREAD

**Issue by sp5wwp** [M17-Project/gr-m17#3]
Can the callsign coder/decoder be added to the block's code? So that the user would just put a string like "AB1CDE" instead of dot separated decimal values?

**Comment by jmfriedt** [comment]
32132356f9fd2e63cbe50e6d19a7788841b3eac0 replaces dot separated 6-byte identifiers with strings, checking the argument length when setting DST and SRC. Also callback functions setting dynamically LSF fields were missing CRC re-calculation after the update. After checking https://spec.m17project.org/part-1/data-link-layer the TYPE field assessment has been replaced from 1-byte to 2-byte (0..65535) value.

**Comment by sp5wwp** [comment]
6-byte identifiers encode up to 9-character strings.

References:
1. https://spec.m17project.org/appendix/address-encoding
2. https://m17project.org/tools/calculator

**Comment by jmfriedt** [comment]
65b634bf18e3341e19c2a64f94c6e268f39914e2 implements the callsign encoding: please check, tested with alphanumeric callsigns and -/. to check consistency.
