### ISSUE TITLE
MD5 checksum mismatch

### ISSUE THREAD

**Issue by sp5wwp** [M17-Project/gr-m17#4]
`m17_decoder_python.cc` has a different MD5 checksum for the `m17_decoder.h` file (as mentioned in the readme).

**Comment by jmfriedt** [comment]
32132356f9fd2e63cbe50e6d19a7788841b3eac0 solves this issue: always make sure to clean build (rm -rf make && mkdir make && cd make && cmake ../) before committing to check the md5sum since this test is performed by cmake and not make.
