### ISSUE TITLE
[Question] about M17 encoder block

### ISSUE THREAD

**Issue by Radiomix2000** [M17-Project/gr-m17#5]
I read the [https://github.com/M17-Project/gr-m17/issues/2#issuecomment-1454694466](url) about relation between input and output items of coder block, but cannot realize, how I should do, if I have 3200 bit/s of input items (infinite stream). There is written about 200 bit/s on input and 24 times more of output items. Can I send more bit/s using M17 encoder. As I mentioned above I need send 3200 bit/s/ Does it mean, that only relation x24 is important? And It's just possible to scale up output items in this case like this: 
3200 bit/s = 1600 symb/s input items. 1600 * 24 = 38400 output samples. How should I do to make this work?

Does M17 encoder block takes packed, unpacked or dibits (pack 2 bits into byte)?

**Comment by jmfriedt** [comment]
Indeed the gr-m17 encoding block knows nothing about input or output rates, it just outputs 24 times more samples than it receives. It is up to you to have a consistent sample rate between input and output (as usual in GNU Radio when interpolating or decimating). As you might see in example/m17_streamer.grc, the input will be a stream of (packed) bytes.
