### ISSUE TITLE
Cross-correlator issue

### ISSUE THREAD

**Issue by sp5wwp** [M17-Project/gr-m17#7]
Currently, the algorithm used to compute `xcorr` is based on standard-deviation-mean approach that is not sensitive to DC-component of the signal nor its amplitude. This property can lead to false syncword detections (example: +3 symbols replaced with +1 will still result in `xcorr` of 1.0).

Proposed solution:
- use the Euclidean norm to estimate the distance between last 8 received symbols and syncword
- if the above step gives a value below a certain threshold, compute soft Hamming distance on recovered softbits and syncword
- if the Hamming distance is below certain threshold, set the `sync` flag

This solution assumes that the DC component is removed from the signal and after the matched root-raised cosine filtering, it passes through {-3, -1, +1, +3} levels. The former can be achieved with a moving average block and subtract block. The latter is guaranteed by the frequency demodulator block and correct RRC filter taps.

Why can't we just use Hamming alone? Because like with the random walk, the average Hamming distance over $`n`$ samples approaches $`\sqrt{n}`$, in our case $`n=16`$ (bits per syncword),
![obraz](https://github.com/M17-Project/gr-m17/assets/44336093/373fe68a-fdc8-4792-b327-1c056435fd8c)
A part of the MATLAB code used to generate the plot above, showing how the noise is applied:
```MATLAB
sync_packet=[3, -3, 3, 3, -3, -3, -3, -3];
sync_bits=[0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1];
sync_test=sync_packet+(rand(1, 8)-0.5)*noise_amp;
```
Noise amplitude is on the horizontal axis. The unit for the vertical axis in the upper plot is in inner deviations, so +1.0 symbols.

Thanks @argilo for pointing this out.

**Comment by sp5wwp** [comment]
This doesn't affect `m17-packet-decoder`, as the application uses L2 norm calculation as proposed above.

**Comment by sp5wwp** [comment]
Fixed. Cross-correlator replaced with Euclidean norm estimation.

**Comment by sp5wwp** [comment]
C++ code needs to be updated. Oops.

**Comment by jmfriedt** [comment]
Please check if you agree with the update brought by 612645ac492c183f89bcf6be130bc68f0c9c55dd: I have replaced the xcorr calculation with the call to ``eucl_norm()`` and its definition. At the moment I have commented the old xcorr calculation but please remove the dead code (comments /* ... */) if the update matches your needs. The modification was not tested other than validating the compilation of the library.

**Comment by jrmeyers** [comment]
in commit 612645a, in m17_decoder_impl.cc, lines 207 and 219 include a constant DIST_THRESH which I haven't been able to find the definition of - what should be used as the value for that constant?

**Comment by jmfriedt** [comment]
```
$ grep -r DIST_THRESH *
M17_Implementations/SP5WWP/inc/m17.h:#define DIST_THRESH         2.0f        //threshold for distance (syncword detection)
```
is the definition of the constant. I have not touched this part of the library.

**Comment by sp5wwp** [comment]
I'm in Ukraine until Oct 8 and will have little to no time to work on this.
Tests over RF are prohibited.
My bet is that after JMF's changes, the code should still work properly.

нд, 24 вер. 2023, 09:02 користувач Jean-Michel Friedt <
***@***.***> пише:

**Comment by jmfriedt** [comment]
Just tested on the virtual loopback and all seems functional.

**Comment by sp5wwp** [comment]
The `Threshold` input field should be used instead of the `#define`' (if it's not already).

**Comment by jmfriedt** [comment]
I am confused: in the initial code the condition was
```
#define XCORR_THRESHOLD 0.90
            if(xcorr>_threshold) // XCORR_THRESHOLD) //Frame syncword detected
            {
...
           }
            else if(xcorr<-_threshold) // XCORR_THRESHOLD) //LSF syncword
            {
...
            }

```
but now we use ``../M17_Implementations/SP5WWP/inc/m17.h:#define DIST_THRESH         2.0f`` and the code reads
```
            if(dist<DIST_THRESH) //frame syncword detected
            {
...
            }
            else
            {   
                //calculate euclidean norm again, this time against LSF syncword
                dist = eucl_norm(last, lsf_sync, 8);
                if(dist<DIST_THRESH) //LSF syncword
...
```
I replaced ``DIST_THRESH`` with the variable set from the block ``_threshold`` but am unsure if that was the original intention.

**Comment by sp5wwp** [comment]
> I replaced `DIST_THRESH` with the variable set from the block `_threshold` but am unsure if that was the original intention.

Yes, that's correct. Now, 0.0 stands for an ideal match.

**Comment by sp5wwp** [comment]
The documentation was updated by JMF just now. Closing again :)
