### ISSUE TITLE
C++ code is redundant

### ISSUE THREAD

**Issue by sp5wwp** [M17-Project/gr-m17#8]
C++ version of the C code pulled as a submodule, is redundant. The aim should be to create some form of API within the C code that could be called from GNU Radio to avoid duplicate code.

**Comment by jmfriedt** [comment]
I would be nice if only ``main()`` could be left in ``M17_Implementations/SP5WWP/m17-coder/m17-coder-sym.c`` and all other functions could be moved to another file the GNU Radio library could be linked against. Similarly if the main() loop could be mostly empty except for reading the file content, then the GNU Radio work() function could rely on the same processing steps.

**Comment by sp5wwp** [comment]
Can we consider this fixed?

**Comment by jmfriedt** [comment]
Would it make sense for ``void send_preamble(const uint8_t type)`` in ``lib/lib.c`` to return ``float *out, int *counterout`` as done in ``gr-m17/lib/m17_coder_impl.cc`` rather than just writing to stdout? Same for ``send_syncword``?

Would it make sense to factor all the finite state machine related to handling ``lich_encoded[]`` in a library function rather than having all this logic exposed in the receiver block?

**Comment by sp5wwp** [comment]
1) Of course, we need to get rid of `stdio.h` functions within the library.
2) You mean wrapping up all the code starting from [here](https://github.com/M17-Project/M17_Implementations/blob/870aa36387c54c9d23c7b678386a0a64ccc59e92/SP5WWP/m17-coder/m17-coder-sym.c#L72C29-L72C29) in a function? Additionally, bit interleaver and randomizer that follow, could be librarified too.

**Comment by sp5wwp** [comment]
1) is done.

**Comment by sp5wwp** [comment]
SRC callsign is malformed. "AB1CDE" should encode to 0x0000**1F24**5D51. "5D-19E" encodes to 0x0000**241F**0000.
![obraz](https://github.com/M17-Project/gr-m17/assets/44336093/316e9837-560f-45ec-af10-d5af73f82950)

**Comment by sp5wwp** [comment]
DST is affected in the same way - order of bytes seems to be reversed.

**Comment by sp5wwp** [comment]
Payload is OK.

**Comment by sp5wwp** [comment]
Can we close this issue now?

**Comment by sp5wwp** [comment]
Everything works fine with libm17.
